chore(tests): warn about missing LDS_TEST_DATABASE_URL envvar

diff --git a/scripts/pretest b/scripts/pretest
--- a/scripts/pretest
+++ b/scripts/pretest
@@ -15,6 +15,12 @@ if [ "$TEST_DATABASE_URL" == "" ]; then
   echo "To resolve this, ensure environmental variable TEST_DATABASE_URL is set"
   exit 1;
 fi;
+if [ "$LDS_TEST_DATABASE_URL" == "" ]; then
+  echo "ERROR: No LDS test database configured; aborting"
+  echo
+  echo "To resolve this, ensure environmental variable LDS_TEST_DATABASE_URL is set"
+  exit 1;
+fi;
 
 SERVER_VERSION_NUM=$(psql -Xqtv ON_ERROR_STOP=1 -c "show server_version_num;" "$TEST_DATABASE_URL")
 
